### ISSUE TITLE
Request for Build Guide/Bill of Parts or Alternative Build Resources

### ISSUE THREAD

**Issue by alikhatibak** [infused-kim/kb_think_corney#1]
Request for Build Guide/Bill of Parts or Alternative Build Resources:

Firstly, I'd like to thank you, @infused-kim, for your incredible work on the zmk drivers for trackpoints, I'm very thankful for all you contributions and excited to get building myself!

I ordered your Think Corney PCB's from JLC PCB a while back and just got them yesterday, went ahead and put in switches and keycaps to get a feel for everything, and I'm super excited.

![IMG_9846](https://github.com/infused-kim/kb_think_corney/assets/25489450/3d960b7e-16cc-4bf4-95a4-026e438c52c8)

Despite this excitement, I am struggling to find resources for building your board, specifically when it comes to setting up the trackpoint module. I am assuming most of the other parts are pretty standard, diodes, nice!nano, nice!view, etc (although confirmation on that would be great) however sourcing everything and having a clear list to cross reference would be incredibly helpful.

If you are able to accommodate adding a Bill of Materials and/or a Build and Configuration Guide, it would be incredibly helpful and would be greatly appreciated by me, and possible others wanting to build their own Think Corney.

Thank you again for everything!

**Comment by infused-kim** [comment]
Thank you so much for the praise and excitement. 

I don’t have plans to create a build guide at the moment, because this is a very, very early design prototype that has quite a lot of flaws. 

Building trackpoint keyboards is a bit of an unpaved road at the moment. 

Primarily because many things haven’t been figured out yet. 

I wouldn’t recommend it as a first build. If you have made keyboards before, then you should be able to figure it out. 

You can find instructions on where to order trackpoints on the zmk discord in the #pointing-devices channel. I think it’s pinned. 

You connect the TP using the ezmate pico connector. The 5-pin cables are a bit hard to source but you can find them on digikey and Ali express. 

One of the biggest flaws of the design is that it requires you to solder tiny wires to the TP PCB. And it turns out the pads are very fragile. So be careful with that step. 

That’s one of the many things I’ll change in a future redesign. But be mindful of it. 

The ezmate pico PCB socket is also a pain in the ass to solder. But if you Google drag soldering you should find usable instructions. 

The controller requires you to solder jumpers on the back of it. You can check the footprint source and search the ergogen discord discussions for more info on that type of controller connector. 

Everything else is pretty standard. But I’m writing this from the top of my head. 

Overall, I recommend double checking everything I said in the kicad file since it’s been a while since I designed it. 

You can find a lot of info in the code and comments of the kicad footprints.

**Comment by alikhatibak** [comment]
Thank you so much, this has been incredibly informative, and that answers most of my questions!

This isn't my first build, and i have a good bit of delicate soldering experience that should come in handy

Thank you again, take care

**Comment by infused-kim** [comment]
You are welcome @alikhatibak. You can also consider ordering an FFC adapter board. That way you can connect the TP with the FPC cable instead of soldering it.

I haven't tried that yet, but that would be more reliable and less error-prone.

**Comment by infused-kim** [comment]
One more thing I remembered just now. The power and reset switch is also totally different from most designs. 

You can check the ergogen footprints for info on which models will work.

**Comment by alikhatibak** [comment]
Thank you so much! I'll definitely consider the FCC board.

I'm struggling to find component names in the footprints, but did some digging and cross-referencing with parts on typeractive.xyz and landed on the `SSSS811101` Power Switch and the `EVQPUC02K` Reset Switch, how could I check if those components would work?

Not sure if I'm missing something, but on my end none of the components have comments/docs with part information, the most I've been able to get is footprint names like `sw_reset_side` and `power_ switch`. Some components have names like `conn_molex_pico_ezmate_1x05` where I can figure out the part from the name, but thats only been for the Molex Pico EZmate Connectors.

The config.yaml was helpful when it came to the SMD 0805 resistors and capacitors

```
# TP clock pull up resistor 4.7k
# TP Reset circuit resistor 100k
# TP Reset circuit capacitor 2.2uF
# TP data pull up resistor 4.7k
```

Is there any chance you have information on the following parts? Have I sourced the right ones? If not, could you point me in the right direction?

| Parts I'm Looking for | Part Numbers and Links |
|----|------|
|SMD Diodes| [1N4148W W1 SOD-123](https://www.aliexpress.us/item/3256803563930483.html?spm=a2g0o.detail.0.0.5b3dvEMVvEMVy7&mp=1&gatewayAdapt=glo2usa)
|Reset Switch| [EVQPUC02K](https://www.aliexpress.us/item/3256802779164165.html?spm=a2g0o.detail.0.0.5b3dvEMVvEMVy7&mp=1&gatewayAdapt=glo2usa)
|Power Switch| [SSSS811101](https://www.aliexpress.us/item/3256805469302826.html?spm=a2g0o.detail.0.0.c1aaB1u7B1u72g&mp=1&gatewayAdapt=glo2usa)


Thank you again for your guidance through this build!

**Comment by infused-kim** [comment]
You can find the actual footprints in this repo:
https://github.com/infused-kim/kb_ergogen_fp

The comments there have model numbers. The power switch from typeractive MIGHT fit, but the reset switch probably won't.

You can verify it by finding the datasheet with the pins and dimensions and compare it to the footprint in kicad.

The diodes should be fine.

I ordered most of my parts from digikey and just realized I have a list that should include most or all the parts:
https://www.digikey.com/en/mylists/list/2CGTLYAVKX

I _think_ these should all be correct, but I am not 100% certain and haven't verified it, especially the quantities of the parts.

**Comment by alikhatibak** [comment]
Thank you so much, that's everything I think I need :) I was also unsure of whether to get the T460S or T440 TP, and the footprints in the linked repo helped me go with the T440.

**Comment by infused-kim** [comment]
I don't have a good recommendation for which TP to use. So far all of them worked for me and I am currently using the red T460S one, because it has the smallest size.

One big downside of it is that it is quite fragile and you can easily pull the pads off it.

I am not sure about the T440 one. I also have a T430, which is much bulkier, but less fragile.

I have ordered a power consumption measuring device and will be able to give better recommendations in the future.

**Comment by infused-kim** [comment]
And this is the reset switch I used:
https://www.digikey.com/en/products/detail/panasonic-electronic-components/EVQ-P7A01P/4429447

I just realized it wasn't on the list.

**Comment by alikhatibak** [comment]
> I don't have a good recommendation for which TP to use. So far all of them worked for me and I am currently using the red T460S one, because it has the smallest size.

Is that the one in the Think Corney? I was worried it might not fit from some discussions in the zmk discord, I like the t460s if it works with the current PCB.

Thank you again, cant wait to get all the components.
